### ISSUE TITLE
Processing PDF

### ISSUE THREAD

**Issue by ufobat** [azawawi/raku-magickwand#10]
you can process PDF with magickwand if you install https://www.ghostscript.com/download/gsdnld.html. Maybe it is worth to mention it in the README.md?

**Comment by azawawi** [comment]
Fixed in https://github.com/azawawi/perl6-magickwand/commit/fc64893fcb5a69c1100868d4c62738c22ff3466f. Thanks :+1:  and sorry for being late on this one.
