### ISSUE TITLE
Can't work out how to get errors

### ISSUE THREAD

**Issue by Altreus** [azawawi/raku-magickwand#14]
I'm guessing maybe this isn't implemented but I can't figure out how to get the error when `read` returns false.

Ideally this would have a more modern, Perl6-y architecture where we would have atomic object creation with exceptions thrown, but any guide on how to get the error string from the magick wand would be helpful, even if it's just done in the examples or tests.

**Comment by azawawi** [comment]
True. Thanks for reporting it. I am sorry I do not have the time these days to fix this.  Any PR would be more than welcome.

`read` (a helper) return result:
https://github.com/azawawi/perl6-magickwand/blob/master/lib/MagickWand.pm6#L73

Actual API is found here with some documentation:
https://github.com/azawawi/perl6-magickwand/blob/master/lib/MagickWand/NativeCall/Image.pm6#L3429

Exception error codes:
Please see http://www.imagemagick.org/www/script/exception.php
