### ISSUE TITLE
Install fails with Cannot locate native library 'CORE_RL_wand_.dll': error 0x7e

### ISSUE THREAD

**Issue by Odud** [azawawi/raku-magickwand#6]
I'm using Windows 10 with Rakudo version 2017.07 and have tried both the 16 and 8 bit depth versions of ImageMagick-7.0.7-7 

Looking in the Image Magick folder I can't see that dll, but there is one called CORE_RL_MagickWand_.dll

Here's the first bit of output from zef with the path shown first

PS C:\WINDOWS\system32> $Env:Path
C:\Program Files\ImageMagick-7.0.7-Q8;C:\ProgramData\Oracle\Java\javapath;C:\ProgramFiles\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows etc. etc.
PS C:\WINDOWS\system32> zef install MagickWand
Use of Nil in string context
  in sub guess-path at C:\rakudo\share\perl6\site\sources\2A928C6F9B02AF49EBD04F99E07BE1820A3A1C9F (Zef::Config) line 21
Use of Nil in string context
  in sub guess-path at C:\rakudo\share\perl6\site\sources\2A928C6F9B02AF49EBD04F99E07BE1820A3A1C9F (Zef::Config) line 21
===> Searching for: MagickWand
===> Searching for missing dependencies: LibraryCheck
===> Testing: LibraryCheck:ver('0.0.6'):auth('github:jonathanstowe')
===> Testing [OK] for LibraryCheck:ver('0.0.6'):auth('github:jonathanstowe')
===> Testing: MagickWand:ver('0.0.2'):auth('github:azawawi')
Cannot locate native library 'CORE_RL_wand_.dll': error 0x7e
  in method setup at C:\rakudo\share\perl6\sources\24DD121B5B4774C04A7084827BFAD92199756E03 (NativeCall) line 316
  in method CALL-ME at C:\rakudo\share\perl6\sources\24DD121B5B4774C04A7084827BFAD92199756E03 (NativeCall) line 328
  in method read at C:\Users\ADMINI~1\AppData\Local\Temp\.zef\store\perl6-magickwand.git\13bc0b051775f74f2422833017915dc
87aebcaec\lib\MagickWand.pm6 (MagickWand) line 72
  in block <unit> at t\02-magickwand.t line 24

**Comment by Odud** [comment]
From the link you provide in the readme it looks like you are expecting an old version of ImageMagick to be installed - is this correct?

**Comment by azawawi** [comment]
@Odud  yup i tested on v6. See [Appyor CI results](https://ci.appveyor.com/project/azawawi/perl6-magickwand/branch/master).

**Comment by Odud** [comment]
Hi, 

I downloaded a copy and have changed it locally so that it seems to work correctly (i.e. the test suite and  01-hello.pl6 and 02-effects.pl6 run ok) with ImageMagick 7.0.7-7. I can't test for Unix and Mac. 

The changes are pretty minor and just involved changing the name of the dll to CORE_RL_MagickWand_.dll (in Common.pm6) and changing all occurrences of MagickSeparateImageChannel to MagickSeparateImage (in Image.pm6 and MagickWand.pm6).

This is fine for my purposes as I will just use my local version, but thought you might find it useful if you ever plan support for v7.

Pete

**Comment by azawawi** [comment]
@Odud Thanks for information :+1: and sorry for the late reply. All will be fixed in the next `0.1.0` cpan release.

**Comment by azawawi** [comment]
Fixed in https://github.com/azawawi/perl6-magickwand/commit/b289e6195e4345e9c1b3699000229126ea27996c and https://github.com/azawawi/perl6-magickwand/commit/8df70bf7bda814da7dea5aaf194d98072880ed5e.
